[servers]
node1
node2

[controller]
control

[frr]
frr1 ansible_host=clab-frr-lab-frr1
frr2 ansible_host=clab-frr-lab-frr2
frr3 ansible_host=clab-frr-lab-frr3

[all:vars]
ansible_user=jeff
ansible_python_interpreter=/usr/bin/python3.14

[controller:vars]
ansible_connection=local

[frr:vars]
ansible_connection=community.docker.docker
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
